# Generated by Django 4.2.11 on 2024-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='student',
            field=models.CharField(max_length=51),
        ),
    ]
