# Generated by Django 4.2.11 on 2024-03-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_jurnal_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
